### ISSUE TITLE
Degenerate filtering fails on tutorial

### ISSUE THREAD

**Issue by luhugerth** [jwdebelius/q2-sidle#3]
$ qiime sidle filter-degenerate-sequences \
  --i-sequences sidle-db-full-sequences.qza \
  --p-max-degen 3 \
  --o-filtered-sequences sidle-db-full-degen-filtered-sequences.qza

```
Plugin error from sidle:

  'int' object has no attribute 'replace'

Debug info has been saved to /tmp/qiime2-q2cli-err-t53wjarh.log
```

 Unfortunately, the log file is empty :confused:

**Comment by luhugerth** [comment]
The same error `'int' object has no attribute 'replace'` appears when running ` qiime sidle prepare-extracted-region`

**Comment by jwdebelius** [comment]
I can't reproduce the error with either qiime2-2020.8 or qiime2-2020.11, but Im also running dask 2.3, so Im not sure if that's the issue? Could you try upgrading your dask and I'll try updating the instructions?
Sorry

**Comment by rsak-384** [comment]
Hello, i have the same error "'int' object has no attribute 'replace'" when running qiime sidle prepare-extracted-region.
Contents of log file:

```
Traceback (most recent call last):
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-221>", line 2, in prepare_extracted_region
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2_sidle/_extract.py", line 75, in prepare_extracted_region
    n_workers=n_workers, address=client_address)
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2_sidle/_utils.py", line 97, in _setup_dask_client
    client = Client()
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/distributed/client.py", line 715, in __init__
    self.start(timeout=timeout)
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/distributed/client.py", line 880, in start
    sync(self.loop, self._start, **kwargs)
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/distributed/utils.py", line 333, in sync
    raise exc.with_traceback(tb)
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/distributed/utils.py", line 317, in f
    result[0] = yield future
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/distributed/client.py", line 946, in _start
    **self._startup_kwargs
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/distributed/deploy/spec.py", line 346, in _
    await self._start()
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/distributed/deploy/spec.py", line 264, in _start
    **self.scheduler_spec.get("options", {})
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/distributed/scheduler.py", line 885, in __init__
    self.bandwidth = parse_bytes(dask.config.get("distributed.scheduler.bandwidth"))
  File "/home/rihards/programmas/mconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/dask/utils.py", line 1164, in parse_bytes
    s = s.replace(" ", "")
AttributeError: 'int' object has no attribute 'replace'
```

**Comment by jwdebelius** [comment]
Thanks @rsak-384. What version of dask are you running? Are you running on linux or mac?

**Comment by rsak-384** [comment]
> 
> 
> Thanks @rsak-384. What version of dask are you running? Are you running on linux or mac?
Hello. 
Dask version 2.3. Might be a docker running debian.

**Comment by jwdebelius** [comment]
I haven't been able to reproduce it on mac, so it may well be a linux issue. I'll check. I'm currently working on the docs in a second branch, and not at the point this is really ready for widespread use?

**Comment by luhugerth** [comment]
Turns out it's a Python3 issue - I made a new env with py=2.7.18, then it works!

**Comment by jwdebelius** [comment]
@luhugerth, that's really weird because I have never tested it with 2.7... only like 3.6. My theory was that it was a backwards compatibility with 2020.8 vs 2020.11... so that's super weird.

**Comment by rsak-384** [comment]
@jwdebelius @luhugerth From what i understand, it has something to do with package versions, which come as dependencies for dask, especially the "distributed" package (something similiar as here https://github.com/dask/dask/issues/5465), but i have yet to find the right combination of package versions, which work.
Maybe @jwdebelius can share the list of conda packages and most importantly their versions, which worked together?

**Comment by jwdebelius** [comment]
I developed against the 2020.11 development release and tested against the 2020.11 release, with a pandas 1.2 update. There were some weird transitions with 2020.8 -> 2020.11, I think. Because that was released shortly before @luhugerth you tried it, I wondered if the issue was the 2020.11 transition. 

It's currently tested against the [qiime2-staging version](https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml), but has been fairly stable with 2020.11 after I did the pandas update two weeks ago. The linux-based test suite is running dask 2.2.

So, I wonder if it's a 2020.8 vs 2020.11 issue, since that's when the pandas update happened. 

And, if it is that version split, then I'll probably update the documents to just require qiime >= 2020.11. The one other weird thing is that at one point, I had a version that liked [RESCRIPt](https://github.com/bokulich-lab/RESCRIPt). But, again, I'm finding it weird because I've been able to run on my mac with 2020.11 and 2020.8 and on our Linux server with 2020.11 without RESCRIPt.

**Comment by luhugerth** [comment]
I managed to accidentally delete my working environment and I can't recreate one now, regardless of which combinations of python version, qiime version and pandas version I use... What I can say is that creating an env using `conda env create -n qiime2-2020.8-py2.7.18 python=2.7.18 --file qiime2-2020.11-py36-linux-conda.yml` still creates an env with python 3.6, so that wasn't it!

I'm attaching a [list of all packages](https://github.com/jwdebelius/q2-sidle/files/5701377/package_version.txt) and versions in my env after running 

```
conda env create -n qiime2-2020.11 --file qiime2-2020.11-py36-linux-conda.yml
conda install dask=2.2 regex
pip install git+https://github.com/jwdebelius/q2-sidle
qiime dev refresh-cache
```

so you can try and pinpoint what package is missing or in the wrong version

**Comment by rsak-384** [comment]
Tried with 2020.11, didn`t work. Also 2020.11 comes with pandas 1.1.5. Pandas 1.2.0 can`t be installed neither with conda install neither with pip/pip3 install, as the newest available version for both is 1.1.5.

**Comment by jwdebelius** [comment]
Thanks @rsak-384; I haven't tested with the virtual box nor Luisa's environment and may not be able to before the new year. So, I've started the run of your data locally and I'll keep troubleshooting this. It bothers me that I can't reproduce the error.

**Comment by jwdebelius** [comment]
Thanks for being patient @rsak-384; I think I've solved it 🤞 with #9

I was able to reproduce the error using the docker container. There are two things that need to be changed with the instructions (and I think I updated in the branch). 

First, use the latest version of dask (`2020.12` worked for me).  
Then, you need to install [RESCRIPt](https://github.com/bokulich-lab/RESCRIPt).

**Comment by jwdebelius** [comment]
Hey @luhugerth, @rsak-384 have you been able to use this version since this was updated?

**Comment by luhugerth** [comment]
Yes, I ran a fresh install today and everything works fine!
