### ISSUE TITLE
Error while testing  Human Oral Microbiome Database (HOMD) 

### ISSUE THREAD

**Issue by elsamdea** [jwdebelius/q2-sidle#31]
I was testing a different database (specifically: Human Oral Microbiome Database or HOMD) with sidle memory-refactor version and I got through an error. For a record, I am using qiime version **qiime2-2021.4**, but I have also tried with others qiime versions as qiime2-2021.11 or qiime2-2021.2. 

 
The command I was running was "qiime sidle reconstruct-database". And it looked good for a while: 

aligment map loaded

database kmers identified

kmer map built

regions grouped

tidying round 1

**Until the next error showed:** 

distributed.worker - WARNING - Compute Failed

Function:  subgraph_callable

[2902 rows x 5 columns])

kwargs:    {}

Exception: ValueError("invalid literal for int() with base 10: '12F'")

Traceback (most recent call last):

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/q2cli/commands.py", line 329, in __call__

    results = action(**arguments)

  File "<decorator-gen-219>", line 2, in reconstruct_database

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/qiime2/sdk/action.py", line 244, in bound_callable

    outputs = self._callable_executor_(scope, callable_args,

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_

    output_views = self._callable(**view_args)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/q2_sidle/_build_database.py", line 141, in reconstruct_database

    shared_check_no1 = shared_check_no1.compute()

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/base.py", line 285, in compute

    (result,) = compute(self, traverse=False, **kwargs)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/base.py", line 567, in compute

    results = schedule(dsk, keys, **kwargs)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/distributed/client.py", line 2673, in get

    results = self.gather(packed, asynchronous=asynchronous, direct=direct)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/distributed/client.py", line 1982, in gather

    return self.sync(

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/distributed/client.py", line 853, in sync

    return sync(

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/distributed/utils.py", line 354, in sync

    raise exc.with_traceback(tb)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/distributed/utils.py", line 337, in f

    result[0] = yield future

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/tornado/gen.py", line 762, in run

    value = future.result()

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/distributed/client.py", line 1847, in _gather

    raise exception.with_traceback(traceback)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/optimization.py", line 966, in __call__

    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/core.py", line 151, in get

    result = _execute_task(task, cache)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task

    return func(*(_execute_task(a, cache) for a in args))

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/core.py", line 121, in <genexpr>

    return func(*(_execute_task(a, cache) for a in args))

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task

    return func(*(_execute_task(a, cache) for a in args))

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/utils.py", line 34, in apply

    return func(*args, **kwargs)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/dataframe/core.py", line 5743, in apply_and_enforce

    df = func(*args, **kwargs)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/dask/utils.py", line 900, in __call__

    return getattr(obj, self.method)(*args, **kwargs)

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/pandas/core/series.py", line 4138, in apply

    mapped = lib.map_infer(values, f, convert=convert_dtype)

  File "pandas/_libs/lib.pyx", line 2467, in pandas._libs.lib.map_infer

  File "/home/elsa/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/q2_sidle/_build_database.py", line 128, in <lambda>

    lambda x: int(x.split("-")[1]),

ValueError: invalid literal for int() with base 10: '12F'

 

Plugin error from sidle:

 

  invalid literal for int() with base 10: '12F'.

I think that, maybe, other people would find interesting the possibility to use another databases instead of SILVA or Greeengenes.

**Comment by jwdebelius** [comment]
Hi @elsamdea,

I am so sorry that this has taken so long. I _think_ this fix should work that I just pushed. Please check and let me know. And, again, Im sorry for the delay. Life has been hectic with an international move

**Comment by elsamdea** [comment]
Hi  @jwdebelius 

I understand the situation (and I hope everything is ok!). I finally obtained the HOMDB reconstruction!!! :)  However, I have to reduce the --p-min-counts  to 1 because I have samples with only 1 or 2 alignments. 

So, this is just a suggestion: Maybe it could be an option to discard (yes or no) the samples with less than 1000 total sequences?

**Comment by jwdebelius** [comment]
I'm going to close this issue if its working. Can the keep/discard go to the issue about counts, just so I can keep track of things.
