### ISSUE TITLE
Error in reconstructing the phylogenetic tree

### ISSUE THREAD

**Issue by wqrao** [jwdebelius/q2-sidle#32]
When I tried to reconstruct the phylogenetic tree, the verbose appeared as follows:
```
Plugin error from sidle:

  "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['A45315.1.1521', 'AACE03000034.3.1790', 'AACF01000230.1893.3681',\n       'AACG02000231.1096.2885', 'AACH01000259.1362.3151',\n       ...\n       'Z96079.1.1495', 'Z96086.1.1496', 'Z96087.1.1498', 'Z96090.1.1485',\n       'Z96095.1.1484'],\n      dtype='object', name='db-seq', length=19282). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

Debug info has been saved to /tmp/qiime2-q2cli-err-ha2byutu.log
```

The qiime2-q2cli-err-ha2byutu.log showed that:
```
Traceback (most recent call last):
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-227>", line 2, in reconstruct_fragment_rep_seqs
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 391, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/q2_sidle/_tree.py", line 82, in reconstruct_fragment_rep_seqs
    aligned_sequences.loc[reconstruction_map.index]
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/pandas/core/indexing.py", line 1053, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/yaoxq/miniconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/pandas/core/indexing.py", line 1321, in _validate_read_indexer
    raise KeyError(
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['A45315.1.1521', 'AACE03000034.3.1790', 'AACF01000230.1893.3681',\n       'AACG02000231.1096.2885', 'AACH01000259.1362.3151',\n       ...\n       'Z96079.1.1495', 'Z96086.1.1496', 'Z96087.1.1498', 'Z96090.1.1485',\n       'Z96095.1.1484'],\n      dtype='object', name='db-seq', length=19282). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
```

How to deal with it?  Thanks for your time and help!

**Comment by jwdebelius** [comment]
Hello, can you please open this as a post on the qiime2 forum as requested in the readme?
